import { Song } from "./types";

export const maryHadALittleLamb: Song = {
  title: 'Mary Had a Little Lamb',
  composer: 'Traditional',
  bpm: 120,
  timeSignature: 4,
  trebleClef: true,
  measures: [
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 1,
      notes: [
        {
          duration: 1,
          name: 'E',
          octave: 4,
          beat: 1,
        },
        {
          duration: 1,
          name: 'D',
          octave: 4,
          beat: 2,
        },
        {
          duration: 1,
          name: 'C',
          octave: 4,
          beat: 3,
        },
        {
          duration: 1,
          name: 'D',
          octave: 4,
          beat: 4,
        },
      ],
    },
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 2,
      notes: [
        {
          duration: 1,
          name: 'E',
          octave: 4,
          beat: 1,
        },
        {
          duration: 1,
          name: 'E',
          octave: 4,
          beat: 2,
        },
        {
          duration: 2,
          name: 'E',
          octave: 4,
          beat: 3,
        },
      ],
    },
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 3,
      notes: [
        {
          duration: 1,
          name: 'D',
          octave: 4,
          beat: 1,
        },
        {
          duration: 1,
          name: 'D',
          octave: 4,
          beat: 2,
        },
        {
          duration: 2,
          name: 'D',
          octave: 4,
          beat: 3,
        },
      ],
    },
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 4,
      notes: [
        {
          duration: 1,
          name: 'E',
          octave: 4,
          beat: 1,
        },
        {
          duration: 1,
          name: 'G',
          octave: 4,
          beat: 2,
        },
        {
          duration: 2,
          name: 'G',
          octave: 4,
          beat: 3,
        },
      ],
    },
  ],
};

export const cMajorScale: Song = {
  title: 'Ascending and Descending C Major Scale',
  composer: 'Generated by AI',
  bpm: 120,
  timeSignature: 4,
  trebleClef: true,
  measures: [
    // First bar: Quarter notes ascending C major scale from middle C
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 1,
      notes: [
        { duration: 1, name: 'C', octave: 4, beat: 1 },
        { duration: 1, name: 'D', octave: 4, beat: 2 },
        { duration: 1, name: 'E', octave: 4, beat: 3 },
        { duration: 1, name: 'F', octave: 4, beat: 4 },
      ],
    },
    // Second bar: Quarter notes continuing ascending C major scale
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 2,
      notes: [
        { duration: 1, name: 'G', octave: 4, beat: 1 },
        { duration: 1, name: 'A', octave: 4, beat: 2 },
        { duration: 1, name: 'B', octave: 4, beat: 3 },
        { duration: 1, name: 'C', octave: 5, beat: 4 },
      ],
    },
    // Third bar: Quarter notes descending C major scale starting on high C
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 3,
      notes: [
        { duration: 1, name: 'C', octave: 5, beat: 1 },
        { duration: 1, name: 'B', octave: 4, beat: 2 },
        { duration: 1, name: 'A', octave: 4, beat: 3 },
        { duration: 1, name: 'G', octave: 4, beat: 4 },
      ],
    },
    // Fourth bar: Quarter notes continuing descending C major scale
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 4,
      notes: [
        { duration: 1, name: 'F', octave: 4, beat: 1 },
        { duration: 1, name: 'E', octave: 4, beat: 2 },
        { duration: 1, name: 'D', octave: 4, beat: 3 },
        { duration: 1, name: 'C', octave: 4, beat: 4 },
      ],
    },
    // Fifth bar: Half notes ascending C major scale from middle C
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 5,
      notes: [
        { duration: 2, name: 'C', octave: 4, beat: 1 },
        { duration: 2, name: 'D', octave: 4, beat: 3 },
      ],
    },
    // Sixth bar: Half notes continuing ascending C major scale
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 6,
      notes: [
        { duration: 2, name: 'E', octave: 4, beat: 1 },
        { duration: 2, name: 'F', octave: 4, beat: 3 },
      ],
    },
    // Seventh bar: Half notes descending C major scale starting on high C
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 7,
      notes: [
        { duration: 2, name: 'G', octave: 4, beat: 1 },
        { duration: 2, name: 'A', octave: 4, beat: 3 },
      ],
    },
    // Eighth bar: Half notes continuing descending C major scale
    {
      timeSignature: 4,
      trebleClef: true,
      measureNumber: 8,
      notes: [
        { duration: 2, name: 'B', octave: 4, beat: 1 },
        { duration: 2, name: 'C', octave: 5, beat: 3 },
      ],
    },
  ],
};
